.TH CAFFEINATED 1 caffeinated\-VERSION
.SH NAME
Caffeinated \- Prevents system idle state
.SH SYNOPSIS
.B caffeinated
.RB [ OPTIONS ]
.SH DESCRIPTION
Caffeinated is a small utility which prevents the system from entering an idle state by taking a systemd logind idle inhibitor lock. It can be run either in the foreground or as a daemon.
.SH OPTIONS
.TP
.B \-h
display help
.TP
.B \-v
display version information
.TP
.B \-d
run as background daemon
.TP
.B \-p PATH
pidfile PATH
.SH SIGNALS
Sending SIGUSR1 will cause caffeinated to enable/disable its idle inhibitor.
.SH AUTHORS
Written by Corey Hinshaw.
.SH COPYRIGHT
Copyright 2019 Corey Hinshaw
.br
License: MIT License - See the LICENSE file for details.
